/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.formdev.flatlaf.FlatLightLaf;
import dao.PaymentsDAO;
import models.Payment;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.math.BigDecimal;
import java.sql.Date;
import javax.swing.ImageIcon;
import java.sql.Timestamp;
import javax.swing.JFrame;

/**
 *
 * @author CJAY
 */
public class ManagePartial extends javax.swing.JFrame {

    /**
     * Creates new form ManagePartial
     */
    public ManagePartial() {
        FlatLightLaf.setup();
        initComponents();
        loadPaymentsTable();
        
        // Set the default close operation to dispose only the current JFrame
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        tblPayments.getSelectionModel().addListSelectionListener(event -> {
    if (!event.getValueIsAdjusting()) {
        int selectedRow = tblPayments.getSelectedRow();
        if (selectedRow != -1) {
            populateFieldsFromSelectedRow(selectedRow);
        }
    }
});
        
        
        
        setTitle("Easy POS"); 
        
         //Center the window
    setLocationRelativeTo(null); 
    
    // Load the icon image
        ImageIcon icon = new ImageIcon("src/icons/shop2.png"); 

    // Set the icon for the frame
     setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        txtBillCode = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtPaymentDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayments = new javax.swing.JTable();
        btnAddPayment = new javax.swing.JButton();
        btnUpdatePayment = new javax.swing.JButton();
        btnDeletePayment = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        btnSearchPayment = new javax.swing.JButton();
        txtPaymentType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Partial Payments");

        txtPaymentID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtBillCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtPaymentDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPaymentDate.setText("YYYY-MM-DD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Payment ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Bill Code");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Payment Type");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Amount Paid");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Payment Date");

        tblPayments.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Bill Code", "Payment Type", "Amount Paid", "Payment Date"
            }
        ));
        jScrollPane1.setViewportView(tblPayments);
        if (tblPayments.getColumnModel().getColumnCount() > 0) {
            tblPayments.getColumnModel().getColumn(2).setResizable(false);
            tblPayments.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAddPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddPayment.setText("Add Payment");
        btnAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPaymentActionPerformed(evt);
            }
        });

        btnUpdatePayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdatePayment.setText("Update Payment");
        btnUpdatePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePaymentActionPerformed(evt);
            }
        });

        btnDeletePayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletePayment.setText("Delete selected");
        btnDeletePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePaymentActionPerformed(evt);
            }
        });

        btnClearFields.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        btnSearchPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchPayment.setText("Search");
        btnSearchPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPaymentActionPerformed(evt);
            }
        });

        txtPaymentType.setText("Card or Cash");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBillCode)
                            .addComponent(txtPaymentID)
                            .addComponent(txtPaymentType, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAmount)
                            .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddPayment)
                        .addGap(41, 41, 41)
                        .addComponent(btnUpdatePayment)
                        .addGap(28, 28, 28)
                        .addComponent(btnDeletePayment)
                        .addGap(34, 34, 34)
                        .addComponent(btnClearFields)
                        .addGap(26, 26, 26)
                        .addComponent(btnSearchPayment)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBillCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPayment)
                    .addComponent(btnUpdatePayment)
                    .addComponent(btnDeletePayment)
                    .addComponent(btnClearFields)
                    .addComponent(btnSearchPayment))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadPaymentsTable() {
    try {
        PaymentsDAO paymentsDAO = new PaymentsDAO();
        List<Payment> payments = paymentsDAO.getAllPayments();
        DefaultTableModel model = (DefaultTableModel) tblPayments.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Payment payment : payments) {
            model.addRow(new Object[]{
                payment.getPaymentID(),
                payment.getBillCode(),
                payment.getPaymentType(),
                payment.getAmount(),
                payment.getPaymentDate()
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error loading payments: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void btnAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPaymentActionPerformed
         try {
        String billCode = txtBillCode.getText();
        String paymentType = txtPaymentType.getText();
        BigDecimal amount = new BigDecimal(txtAmount.getText());
        Timestamp paymentDate = Timestamp.valueOf(txtPaymentDate.getText()); // Assuming date is in "YYYY-MM-DD HH:MM:SS" format

        Payment payment = new Payment();
        payment.setBillCode(billCode);
        payment.setPaymentType(paymentType);
        payment.setAmount(amount);
        payment.setPaymentDate(paymentDate);

        PaymentsDAO paymentsDAO = new PaymentsDAO();
        paymentsDAO.addPayment(payment);

        JOptionPane.showMessageDialog(this, "Payment added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadPaymentsTable();
        clearFields();
    } catch (SQLException | IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAddPaymentActionPerformed

    private void btnUpdatePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePaymentActionPerformed
       try {
        int selectedRow = tblPayments.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a payment to update.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int paymentID = Integer.parseInt(txtPaymentID.getText());
        String billCode = txtBillCode.getText();
        String paymentType = txtPaymentType.getText();
        BigDecimal amount = new BigDecimal(txtAmount.getText());
        Timestamp paymentDate = Timestamp.valueOf(txtPaymentDate.getText());

        Payment payment = new Payment();
        payment.setPaymentID(paymentID);
        payment.setBillCode(billCode);
        payment.setPaymentType(paymentType);
        payment.setAmount(amount);
        payment.setPaymentDate(paymentDate);

        PaymentsDAO paymentsDAO = new PaymentsDAO();
        paymentsDAO.updatePayment(payment);

        JOptionPane.showMessageDialog(this, "Payment updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadPaymentsTable();
        clearFields();
    } catch (SQLException | IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdatePaymentActionPerformed

    private void btnDeletePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePaymentActionPerformed
        try {
        int selectedRow = tblPayments.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a payment to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int paymentID = Integer.parseInt(txtPaymentID.getText());

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this payment?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            PaymentsDAO paymentsDAO = new PaymentsDAO();
            paymentsDAO.deletePayment(paymentID);

            JOptionPane.showMessageDialog(this, "Payment deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadPaymentsTable();
            clearFields();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnDeletePaymentActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void btnSearchPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPaymentActionPerformed
      try {
        String searchText = txtBillCode.getText().trim();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Bill Code to search.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PaymentsDAO paymentsDAO = new PaymentsDAO();
        List<Payment> payments = paymentsDAO.getAllPayments();
        DefaultTableModel model = (DefaultTableModel) tblPayments.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Payment payment : payments) {
            if (payment.getBillCode().equalsIgnoreCase(searchText)) {
                model.addRow(new Object[]{
                    payment.getPaymentID(),
                    payment.getBillCode(),
                    payment.getPaymentType(),
                    payment.getAmount(),
                    payment.getPaymentDate()
                });
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSearchPaymentActionPerformed
    
    private void clearFields() {
    txtPaymentID.setText("");
    txtBillCode.setText("");
    txtPaymentType.setText("");
    txtAmount.setText("");
    txtPaymentDate.setText("");
}   
    
   private void populateFieldsFromSelectedRow(int selectedRow) {
    txtPaymentID.setText(tblPayments.getValueAt(selectedRow, 0).toString());
    txtBillCode.setText(tblPayments.getValueAt(selectedRow, 1).toString());
    txtPaymentType.setText(tblPayments.getValueAt(selectedRow, 2).toString());
    txtAmount.setText(tblPayments.getValueAt(selectedRow, 3).toString());
    txtPaymentDate.setText(tblPayments.getValueAt(selectedRow, 4).toString());
} 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePartial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePartial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePartial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePartial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePartial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPayment;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnDeletePayment;
    private javax.swing.JButton btnSearchPayment;
    private javax.swing.JButton btnUpdatePayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayments;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBillCode;
    private javax.swing.JTextField txtPaymentDate;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextField txtPaymentType;
    // End of variables declaration//GEN-END:variables
}
