/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.ItemDAO;
import dao.ReturnItemDAO;
import dao.SupplierDAO;
import models.Item;
import models.ReturnItem;
import models.Supplier;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.time.LocalDate; // Make sure to import LocalDate


/**
 *
 * @author CJAY
 */
public class ReturnItems extends javax.swing.JFrame {
    
    private Map<String, Integer> supplierMap = new HashMap<>(); // Map for supplier ID and names
    private List<Item> allItems;
    private SupplierDAO supplierDAO = new SupplierDAO(); // DAO for supplier operations
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form ReturnItems
     */
    public ReturnItems() {
        initComponents();
         addReturnItemListeners();
        initializeItemList();
        loadItemsTable();
        populateSuppliers();
        
        
         // Set the default close operation to dispose only the current JFrame
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReturn = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbtnNew = new javax.swing.JRadioButton();
        rbtnOld = new javax.swing.JRadioButton();
        txtItemCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        cmbSupplier = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();
        cmbReturnReason = new javax.swing.JComboBox<>();
        btnProcessReturn = new javax.swing.JButton();
        btnDeleteReturn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnUpdateReturn = new javax.swing.JButton();
        btnYearlyReport = new javax.swing.JToggleButton();
        btnQuarterlyReport = new javax.swing.JButton();
        btnMonthlyReport = new javax.swing.JButton();
        btnDailyReport = new javax.swing.JButton();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        tblReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Return Quantity", "Retun Reason", "Supplier", "Stock Type"
            }
        ));
        jScrollPane1.setViewportView(tblReturn);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Item Code");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Return Quantity");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Return Reason ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Supplier");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Stock Type");

        rbtnNew.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtnNew.setText("New");

        rbtnOld.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtnOld.setText("Old");

        txtItemCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtItemName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cmbSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Supplier" }));

        spnQuantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cmbReturnReason.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbReturnReason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Damaged", "Expired", "Exchange", "Other" }));

        btnProcessReturn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnProcessReturn.setText("Process Return");
        btnProcessReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessReturnActionPerformed(evt);
            }
        });

        btnDeleteReturn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDeleteReturn.setText("Delete Return");
        btnDeleteReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReturnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Returns");
        jLabel4.setToolTipText("");

        btnUpdateReturn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdateReturn.setText("Update Return");
        btnUpdateReturn.setToolTipText("");
        btnUpdateReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateReturnActionPerformed(evt);
            }
        });

        btnYearlyReport.setText("Yearly Report");

        btnQuarterlyReport.setText("Quarterly Report");

        btnMonthlyReport.setText("Monthly Report");

        btnDailyReport.setText("Daily Report");

        jLabel8.setText("Start Date");

        jLabel9.setText("End Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemCode)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnNew)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnOld))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbSupplier, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbReturnReason, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProcessReturn)
                                    .addComponent(btnDeleteReturn)
                                    .addComponent(btnUpdateReturn))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMonthlyReport)
                            .addComponent(btnDailyReport)
                            .addComponent(btnYearlyReport)
                            .addComponent(btnQuarterlyReport)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(cmbReturnReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rbtnNew)
                                            .addComponent(rbtnOld)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProcessReturn)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteReturn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdateReturn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnDailyReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMonthlyReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuarterlyReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnYearlyReport)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessReturnActionPerformed
        processReturnItem();
    }//GEN-LAST:event_btnProcessReturnActionPerformed

    private void btnDeleteReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReturnActionPerformed
        deleteReturnItem();
    }//GEN-LAST:event_btnDeleteReturnActionPerformed

    private void btnUpdateReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateReturnActionPerformed
        updateReturnItem();
    }//GEN-LAST:event_btnUpdateReturnActionPerformed
    
    
   private void processReturnItem() {
        try {
            String itemCode = txtItemCode.getText().trim();
            String itemName = txtItemName.getText().trim();
            int returnQuantity = (int) spnQuantity.getValue();
            String returnReason = (String) cmbReturnReason.getSelectedItem();
            String supplier = (String) cmbSupplier.getSelectedItem();

            String stockType = rbtnNew.isSelected() ? "New" : rbtnOld.isSelected() ? "Old" : "";
            if (stockType.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a stock type.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (itemCode.isEmpty() || itemName.isEmpty() || returnQuantity <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter valid item details.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ReturnItemDAO returnItemDAO = new ReturnItemDAO();
            ItemDAO itemDAO = new ItemDAO();
            Item item = itemDAO.getByCode(itemCode);
            if (item == null || returnQuantity > item.getQuantity()) {
                JOptionPane.showMessageDialog(this, "Invalid return quantity or item not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ReturnItem returnItem = new ReturnItem(itemCode, itemName, returnQuantity, returnReason, supplier, stockType, LocalDate.now());
            if (!returnItemDAO.saveReturnItem(returnItem)) {
                JOptionPane.showMessageDialog(this, "Failed to process return item.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            item.setQuantity(item.getQuantity() - returnQuantity);
            itemDAO.updateItem(item);
            JOptionPane.showMessageDialog(this, "Return processed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadItemsTable();
            clearFields();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    
   
   public void exportFilteredExcel() {
    try {
        String startDate = txtStartDate.getText().trim();
        String endDate = txtEndDate.getText().trim();
        if (startDate.isEmpty() || endDate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both start and end dates.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<ReturnItem> returnItems = new ReturnItemDAO().getReturnItemsByDateRange(startDate, endDate);
        if (returnItems.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No return items found in this period.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File("Return_Report.xlsx"));
        if (fileChooser.showSaveDialog(null) != JFileChooser.APPROVE_OPTION) return;

        File fileToSave = fileChooser.getSelectedFile();
        try (Workbook workbook = new HSSFWorkbook(); FileOutputStream fileOut = new FileOutputStream(fileToSave)) {
            Sheet sheet = workbook.createSheet("Filtered Return Items");
            String[] headers = {"Item Code", "Item Name", "Quantity", "Return Reason", "Supplier", "Stock Type"};
            Row headerRow = sheet.createRow(0);

            for (int i = 0; i < headers.length; i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(headers[i]);
                CellStyle style = workbook.createCellStyle();
                Font font = workbook.createFont();
                font.setBold(true);
                style.setFont(font);
                cell.setCellStyle(style);
            }

            int rowNum = 1;
            for (ReturnItem item : returnItems) {
                Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(item.getItemCode());
                row.createCell(1).setCellValue(item.getItemName());
                row.createCell(2).setCellValue(item.getReturnQuantity());
                row.createCell(3).setCellValue(item.getReturnReason());
                row.createCell(4).setCellValue(item.getSupplier());
                row.createCell(5).setCellValue(item.getStockType());
            }

            for (int i = 0; i < headers.length; i++) {
                sheet.autoSizeColumn(i);
            }

            workbook.write(fileOut);
            JOptionPane.showMessageDialog(null, "Excel report generated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (IOException | SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    private void addReturnItemListeners() {
        txtItemName.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                showItemNameSuggestions();
            }
        });
        
        tblReturn.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        loadSelectedReturnItem(); // Call the method when a row is clicked
    }
});
        
        
        btnDailyReport.addActionListener(e -> {
    Calendar cal = Calendar.getInstance();
    String today = sdf.format(cal.getTime());
    txtStartDate.setText(today);
    txtEndDate.setText(today);
    exportFilteredExcel();
});

btnMonthlyReport.addActionListener(e -> {
    Calendar cal = Calendar.getInstance();
    cal.set(Calendar.DAY_OF_MONTH, 1);
    String start = sdf.format(cal.getTime());
    cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
    String end = sdf.format(cal.getTime());
    txtStartDate.setText(start);
    txtEndDate.setText(end);
    exportFilteredExcel();
});

btnQuarterlyReport.addActionListener(e -> {
    Calendar cal = Calendar.getInstance();
    int currentMonth = cal.get(Calendar.MONTH);
    int quarterStartMonth = (currentMonth / 3) * 3;
    cal.set(Calendar.MONTH, quarterStartMonth);
    cal.set(Calendar.DAY_OF_MONTH, 1);
    String start = sdf.format(cal.getTime());
    cal.add(Calendar.MONTH, 2);
    cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
    String end = sdf.format(cal.getTime());
    txtStartDate.setText(start);
    txtEndDate.setText(end);
    exportFilteredExcel();
});

btnYearlyReport.addActionListener(e -> {
    Calendar cal = Calendar.getInstance();
    cal.set(Calendar.MONTH, Calendar.JANUARY);
    cal.set(Calendar.DAY_OF_MONTH, 1);
    String start = sdf.format(cal.getTime());
    cal.set(Calendar.MONTH, Calendar.DECEMBER);
    cal.set(Calendar.DAY_OF_MONTH, 31);
    String end = sdf.format(cal.getTime());
    txtStartDate.setText(start);
    txtEndDate.setText(end);
    exportFilteredExcel();
});
        
        
        
        
    }

    private void deleteReturnItem() {
    int selectedRow = tblReturn.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select an item to delete.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        String itemCode = (String) tblReturn.getValueAt(selectedRow, 0);
        int returnQuantity = (int) tblReturn.getValueAt(selectedRow, 2);

        ReturnItemDAO returnItemDAO = new ReturnItemDAO();
        ItemDAO itemDAO = new ItemDAO();

        // Step 1: Restore stock in the Items table
        Item item = itemDAO.getByCode(itemCode);
        if (item != null) {
            item.setQuantity(item.getQuantity() + returnQuantity);
            itemDAO.updateItem(item);
        }

        // Step 2: Delete the return item from ReturnItems table
        if (!returnItemDAO.deleteReturnItem(itemCode)) {
            JOptionPane.showMessageDialog(this, "Failed to delete return item.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Remove from UI table
        ((DefaultTableModel) tblReturn.getModel()).removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Return item deleted and stock restored.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}



    private void showItemNameSuggestions() {
        if (allItems == null || allItems.isEmpty()) {
            initializeItemList();
        }

        String input = txtItemName.getText().trim();
        if (input.isEmpty()) return;

        List<Item> filteredItems = allItems.stream()
            .filter(i -> i.getName().toLowerCase().contains(input.toLowerCase()))
            .toList();

        if (filteredItems.isEmpty()) return;

        JPopupMenu suggestions = new JPopupMenu();
        for (Item item : filteredItems) {
            JMenuItem menuItem = new JMenuItem(item.getName() + " - Retail: " + item.getRetailPrice());
            menuItem.addActionListener(evt -> populateItemFields(item));
            suggestions.add(menuItem);
        }
        suggestions.show(txtItemName, 0, txtItemName.getHeight());
    }

    private void populateItemFields(Item item) {
        txtItemName.setText(item.getName());
        txtItemCode.setText(item.getItemCode());
        if (item.isOldStock()) {
            rbtnOld.setSelected(true);
        } else {
            rbtnNew.setSelected(true);
        }
        cmbSupplier.setSelectedItem(item.getSupplierID());
        
    }

    private void loadItemsTable() {
        try {
            ReturnItemDAO returnItemDAO = new ReturnItemDAO();
            List<ReturnItem> returnItems = returnItemDAO.getAll();
            DefaultTableModel model = (DefaultTableModel) tblReturn.getModel();
            model.setRowCount(0);

            for (ReturnItem item : returnItems) {
                model.addRow(new Object[]{
                        item.getItemCode(),
                        item.getItemName(),
                        item.getReturnQuantity(),
                        item.getReturnReason(),
                        item.getSupplier(),
                        item.getStockType()
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading return items: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearFields() {
        txtItemName.setText("");
        txtItemCode.setText("");
        spnQuantity.setValue(0);
        cmbSupplier.setSelectedIndex(0);
        rbtnNew.setSelected(true);
    }

    private void initializeItemList() {
        try {
            ItemDAO itemDAO = new ItemDAO();
            allItems = itemDAO.getAll();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading items.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String getSupplierName(int supplierID) {
        return supplierMap.entrySet()
                .stream()
                .filter(entry -> entry.getValue().equals(supplierID))
                .map(Map.Entry::getKey)
                .findFirst()
                .orElse("Unknown");
    }

    private void populateSuppliers() {
        try {
            List<Supplier> suppliers = new dao.SupplierDAO().getAll();
            cmbSupplier.removeAllItems();
            supplierMap.clear();
            for (Supplier supplier : suppliers) {
                cmbSupplier.addItem(supplier.getName());
                supplierMap.put(supplier.getName(), supplier.getSupplierID());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading suppliers: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
        // Load selected item details into input fields
    private void loadSelectedReturnItem() {
    int selectedRow = tblReturn.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select an item.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblReturn.getModel();
    
    // Load values into text fields
    txtItemCode.setText((String) model.getValueAt(selectedRow, 0)); // Item Code
    txtItemName.setText((String) model.getValueAt(selectedRow, 1)); // Item Name
    spnQuantity.setValue((int) model.getValueAt(selectedRow, 2)); // Quantity
    cmbReturnReason.setSelectedItem(model.getValueAt(selectedRow, 3)); // Return Reason
    cmbSupplier.setSelectedItem(model.getValueAt(selectedRow, 4)); // Supplier
    
    // Set radio buttons based on stock type
    String stockType = (String) model.getValueAt(selectedRow, 5);
    if ("New".equals(stockType)) {
        rbtnNew.setSelected(true);
    } else if ("Old".equals(stockType)) {
        rbtnOld.setSelected(true);
    }
}

// Update return item details
private void updateReturnItem() {
    try {
        int selectedRow = tblReturn.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to update.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get updated input values
        String itemCode = txtItemCode.getText().trim();
        String itemName = txtItemName.getText().trim();
        int newReturnQuantity = (int) spnQuantity.getValue();
        String returnReason = cmbReturnReason.getSelectedItem().toString();
        String supplier = cmbSupplier.getSelectedItem().toString();

        // Determine the selected stock type
        String stockType;
        if (rbtnNew.isSelected()) {
            stockType = "New";
        } else if (rbtnOld.isSelected()) {
            stockType = "Old";
        } else {
            JOptionPane.showMessageDialog(this, "Please select a stock type.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate inputs
        if (itemCode.isEmpty() || itemName.isEmpty() || newReturnQuantity <= 0 || returnReason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter valid item details.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ReturnItemDAO returnItemDAO = new ReturnItemDAO();
        ItemDAO itemDAO = new ItemDAO();

        // Retrieve the original item to check its stock
        Item item = itemDAO.getByCode(itemCode);
        if (item == null) {
            JOptionPane.showMessageDialog(this, "Item not found in inventory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the original return quantity from the table before updating
        DefaultTableModel model = (DefaultTableModel) tblReturn.getModel();
        int oldReturnQuantity = (int) model.getValueAt(selectedRow, 2);

        // Adjust stock based on quantity change
        int quantityDifference = newReturnQuantity - oldReturnQuantity;
        if (quantityDifference > 0 && quantityDifference > item.getQuantity()) {
            JOptionPane.showMessageDialog(this, "New return quantity exceeds available stock.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update stock quantity
        item.setQuantity(item.getQuantity() - quantityDifference);
        itemDAO.updateItem(item);

        // Update the return item in the database
        ReturnItem updatedReturnItem = new ReturnItem(itemCode, itemName, newReturnQuantity, returnReason, supplier, stockType, LocalDate.now());
        boolean isUpdated = returnItemDAO.updateReturnItem(updatedReturnItem);

        if (!isUpdated) {
            JOptionPane.showMessageDialog(this, "Failed to update return item.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Refresh table
        model.setValueAt(newReturnQuantity, selectedRow, 2);
        model.setValueAt(returnReason, selectedRow, 3);
        model.setValueAt(supplier, selectedRow, 4);
        model.setValueAt(stockType, selectedRow, 5);

        JOptionPane.showMessageDialog(this, "Return item updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadItemsTable();
        clearFields();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}

    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDailyReport;
    private javax.swing.JButton btnDeleteReturn;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnProcessReturn;
    private javax.swing.JButton btnQuarterlyReport;
    private javax.swing.JButton btnUpdateReturn;
    private javax.swing.JToggleButton btnYearlyReport;
    private javax.swing.JComboBox<String> cmbReturnReason;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnNew;
    private javax.swing.JRadioButton rbtnOld;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTable tblReturn;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
