/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import models.User;

import dao.UserDAO;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.User;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author CJAY
 */
public class UserManagementUI extends javax.swing.JFrame {
    
    
    private UserDAO userDAO = new UserDAO(); // DAO for user operations
    private byte[] userPicture; // Stores the picture as a byte array

    /**
     * Creates new form UserManagementUI
     */
    public UserManagementUI() {
        FlatLightLaf.setup();
        initComponents();
        loadUsersTable();
        
        // Set the default close operation to dispose only the current JFrame
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        setTitle("Easy POS"); 
        
         //Center the window
    setLocationRelativeTo(null); 
    
    // Load the icon image
        ImageIcon icon = new ImageIcon("src/icons/shop2.png"); 

    // Set the icon for the frame
     setIconImage(icon.getImage());
        
        
        
        tblUsers.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = tblUsers.getSelectedRow();
                if (selectedRow != -1) {
                    populateFieldsFromSelectedRow(selectedRow);
                }
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtAddres = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmbRole = new javax.swing.JComboBox<>();
        btnAddUser = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        btnBrowsePicture = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1180, 720));
        setMinimumSize(new java.awt.Dimension(1180, 720));
        setPreferredSize(new java.awt.Dimension(1180, 720));

        txtName.setText("Name");
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtUsername.setText("Username");

        txtContactNumber.setText("ContactNumber");

        txtPassword.setText("jPasswordField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtAddres.setViewportView(jTextArea1);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee" }));

        btnAddUser.setText("Add");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        lblPicture.setText("Picture");
        lblPicture.setAlignmentX(0.5F);
        lblPicture.setAutoscrolls(true);
        lblPicture.setMaximumSize(new java.awt.Dimension(100, 100));
        lblPicture.setMinimumSize(new java.awt.Dimension(100, 100));
        lblPicture.setPreferredSize(new java.awt.Dimension(100, 100));

        btnDeleteUser.setText("Delete");
        btnDeleteUser.setToolTipText("");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnUpdateUser.setText("Update");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        btnBrowsePicture.setText("Browse");
        btnBrowsePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePictureActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Contact number");

        jLabel5.setText("Address");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Password", "Contact Number", "Address", "Role", "Picture"
            }
        ));
        jScrollPane2.setViewportView(tblUsers);
        if (tblUsers.getColumnModel().getColumnCount() > 0) {
            tblUsers.getColumnModel().getColumn(5).setResizable(false);
            tblUsers.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtAddres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBrowsePicture)
                        .addGap(18, 18, 18)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUpdateUser, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnClearFields))
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddUser)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteUser))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnClearFields))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnBrowsePicture))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    
    /**
     * Validates if password contains both letters and numbers
     * @param password The password to validate
     * @return true if password is valid, false otherwise
     */
    private boolean isValidPassword(String password) {
        if (password == null || password.trim().isEmpty()) {
            return false;
        }
        
        boolean hasLetter = false;
        boolean hasDigit = false;
        
        for (char c : password.toCharArray()) {
            if (Character.isLetter(c)) {
                hasLetter = true;
            } else if (Character.isDigit(c)) {
                hasDigit = true;
            }
            
            // Early exit if both conditions are met
            if (hasLetter && hasDigit) {
                return true;
            }
        }
        
        return hasLetter && hasDigit;
    }
     
      private void loadUsersTable() {
        try {
            List<User> users = userDAO.getAll();
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setRowCount(0); // Clear existing rows

            for (User user : users) {
                model.addRow(new Object[]{
                    user.getUserID(),
                    user.getName(),
                    user.getUsername(),
                    user.getPassword(),
                    user.getContactNumber(),
                    user.getAddress(),
                    user.getRole(),
                    user.getPicture()                    
                    
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void populateFieldsFromSelectedRow(int selectedRow) {
        try {
            int userID = (int) tblUsers.getValueAt(selectedRow, 0);
            User user = userDAO.getById(userID);

            if (user != null) {
                txtName.setText(user.getName());
                txtUsername.setText(user.getUsername());
                txtPassword.setText(user.getPassword());
                txtContactNumber.setText(user.getContactNumber());
                jTextArea1.setText(user.getAddress());
                cmbRole.setSelectedItem(user.getRole());

                byte[] picture = user.getPicture();
                if (picture != null) {
                    lblPicture.setIcon(new ImageIcon(new ImageIcon(picture).getImage().getScaledInstance(lblPicture.getWidth(), lblPicture.getHeight(), Image.SCALE_SMOOTH)));
                    lblPicture.setText("");
                } else {
                    lblPicture.setIcon(null);
                    lblPicture.setText("No Picture Selected");
                }

                userPicture = picture;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error populating fields: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearFields() {
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtContactNumber.setText("");
        jTextArea1.setText("");
        cmbRole.setSelectedIndex(-1);
        lblPicture.setIcon(null);
        lblPicture.setText("No Picture Selected");
        userPicture = null;
    }

    
    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
            String name = txtName.getText();
            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());
            String contactNumber = txtContactNumber.getText();
            String address = jTextArea1.getText();
            String role = (String) cmbRole.getSelectedItem();

            if (name.isEmpty() || username.isEmpty() || password.isEmpty() || role == null) {
                throw new Exception("All mandatory fields must be filled.");
            }
            
            // Validate password contains both letters and numbers
            if (!isValidPassword(password)) {
                JOptionPane.showMessageDialog(this, 
                    "Password must contain both letters and numbers.\nPlease use a combination of both for security.", 
                    "Invalid Password", 
                    JOptionPane.WARNING_MESSAGE);
                txtPassword.requestFocus();
                return;
            }

            User user = new User();
            user.setName(name);
            user.setUsername(username);
            user.setPassword(password);
            user.setContactNumber(contactNumber);
            user.setAddress(address);
            user.setRole(role);
            user.setPicture(userPicture);

            if (userDAO.add(user)) {
                JOptionPane.showMessageDialog(this, "User added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadUsersTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add user.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {                                              
           try {
            int selectedRow = tblUsers.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select a user to update.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int userID = (int) tblUsers.getValueAt(selectedRow, 0);
            String name = txtName.getText();
            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());
            String contactNumber = txtContactNumber.getText();
            String address = jTextArea1.getText();
            String role = (String) cmbRole.getSelectedItem();

            if (name.isEmpty() || username.isEmpty() || password.isEmpty() || role == null) {
                throw new Exception("All mandatory fields must be filled.");
            }
            
            // Validate password contains both letters and numbers
            if (!isValidPassword(password)) {
                JOptionPane.showMessageDialog(this, 
                    "Password must contain both letters and numbers.\nPlease use a combination of both for security.", 
                    "Invalid Password", 
                    JOptionPane.WARNING_MESSAGE);
                txtPassword.requestFocus();
                return;
            }

            User user = new User();
            user.setUserID(userID);
            user.setName(name);
            user.setUsername(username);
            user.setPassword(password);
            user.setContactNumber(contactNumber);
            user.setAddress(address);
            user.setRole(role);
            user.setPicture(userPicture);

            if (userDAO.update(user)) {
                JOptionPane.showMessageDialog(this, "User updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadUsersTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                             

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {                                              
      try {
            int selectedRow = tblUsers.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select a user to delete.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int userID = (int) tblUsers.getValueAt(selectedRow, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                if (userDAO.delete(userID)) {
                    JOptionPane.showMessageDialog(this, "User deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadUsersTable();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete user.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                             

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {                                               
         clearFields();
    }                                              

    private void btnBrowsePictureActionPerformed(java.awt.event.ActionEvent evt) {                                                 
          try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "png", "jpg", "jpeg"));
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                userPicture = Files.readAllBytes(file.toPath());
                lblPicture.setIcon(new ImageIcon(new ImageIcon(file.getAbsolutePath()).getImage().getScaledInstance(lblPicture.getWidth(), lblPicture.getHeight(), Image.SCALE_SMOOTH)));
                lblPicture.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error selecting picture: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBrowsePicture;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTable tblUsers;
    private javax.swing.JScrollPane txtAddres;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration                   
}